config/routes.rb
Rails.application.routes.draw do
  get 'solagram/index'
  get 'solagram/show'
  root to: 'home#index'
  
  #sola-nows
  resources :satelights
  get 'nows', to: 'nows#index'
  get 'getimage', to: 'nows#getimage' #all data download to up s3

  #sola-data
  get 'data',to: 'data#index'
  get 'data/show'

    #sola-data
    get 'solagram',to: 'solagram#index'
    get 'solagram/show'

  #sola-calender
  resources :calenders
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/calender.rb
class Calender < ApplicationRecord
end

app/controllers/calenders_controller.rb
class CalendersController < ApplicationController
  before_action :set_calender, only: [:show, :edit, :update, :destroy]

  # GET /calenders
  # GET /calenders.json
  def index
    @calenders = Calender.all
    @path = "https://satelights.s3-ap-northeast-1.amazonaws.com"
    p @calenders
  end

  # GET /calenders/1
  # GET /calenders/1.json
  def show
  end

  # GET /calenders/new
  def new
    @calender = Calender.new
  end

  # GET /calenders/1/edit
  def edit
  end

  # POST /calenders
  # POST /calenders.json
  def create
    @calender = Calender.new(calender_params)

    respond_to do |format|
      if @calender.save
        format.html { redirect_to @calender, notice: 'Calender was successfully created.' }
        format.json { render :show, status: :created, location: @calender }
      else
        format.html { render :new }
        format.json { render json: @calender.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calenders/1
  # PATCH/PUT /calenders/1.json
  def update
    respond_to do |format|
      if @calender.update(calender_params)
        format.html { redirect_to @calender, notice: 'Calender was successfully updated.' }
        format.json { render :show, status: :ok, location: @calender }
      else
        format.html { render :edit }
        format.json { render json: @calender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calenders/1
  # DELETE /calenders/1.json
  def destroy
    @calender.destroy
    respond_to do |format|
      format.html { redirect_to calenders_url, notice: 'Calender was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calender
      @calender = Calender.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calender_params
      params.require(:calender).permit(:name, :start_time)
    end
end

app/helpers/calenders_helper.rb
module CalendersHelper
end

app/views/calenders/_form.html.erb
<%= form_with(model: calender, local: true) do |form| %>
  <% if calender.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(calender.errors.count, "error") %> prohibited this calender from being saved:</h2>

      <ul>
      <% calender.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/calenders/edit.html.erb
<h1>Editing Calender</h1>

<%= render 'form', calender: @calender %>

<%= link_to 'Show', @calender %> |
<%= link_to 'Back', calenders_path %>

app/views/calenders/index.html.erb
<p id="notice"><%= notice %></p>


<body>
<div class="container">

<%# 　紹介文　 %>
<div class="container d-flex　align-items-center">
  <h3 class="font-weight-bold text-left"><span class="title">Arcive</span></h3>
  <h3>weather data save SLIDE-SHOW</h3>
  <%# <h3 class="font-weight-bold text-center"><%= @datas.created_at%>
</div>

<table>


<tbody>
<%# calender view %>
  <%= month_calendar events: @calenders do |date, calenders| %>
    <%= date %>
    <%# <%= calenders %>

    <% calenders.each do |calender| %>
      <div>
        <%= image_tag "#{@path}/#{calender.photo1}", :size =>'200x200'%>
        <%# <p><%= "#{@path}/#{calender.photo1}"%>
        <%# <%= calender.photo1 %>
      </div>
    <% end %>
  <% end %>

<%# defaut views %>
    <%#<% @calenders.each do |calender| %>
</tbody>
</table>

<br>

<%= link_to 'New Calender', new_calender_path %>

</div>
</body>

app/views/calenders/new.html.erb
<h1>New Calender</h1>

<%= render 'form', calender: @calender %>

<%= link_to 'Back', calenders_path %>

app/views/calenders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @calender.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @calender.start_time %>
</p>

<%= link_to 'Edit', edit_calender_path(@calender) %> |
<%= link_to 'Back', calenders_path %>