config/routes.rb
Rails.application.routes.draw do
  get 'solagram/index'
  get 'solagram/show'
  root to: 'home#index'
  
  #sola-nows
  resources :satelights
  get 'nows', to: 'nows#index'
  get 'getimage', to: 'nows#getimage' #all data download to up s3

  #sola-data
  get 'data',to: 'data#index'
  get 'data/show'

    #sola-data
    get 'solagram',to: 'solagram#index'
    get 'solagram/show'

  #sola-calender
  resources :calenders
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/satelight.rb
class Satelight < ApplicationRecord
end

app/controllers/satelights_controller.rb
class SatelightsController < ApplicationController
  before_action :set_satelight, only: [:show, :edit, :update, :destroy]

  # GET /satelights
  # GET /satelights.json
  def index
    @satelights = Satelight.all
  end

  # GET /satelights/1
  # GET /satelights/1.json
  def show
  end

  # GET /satelights/new
  def new
    @satelight = Satelight.new
  end

  # GET /satelights/1/edit
  def edit
  end

  # POST /satelights
  # POST /satelights.json
  def create
    @satelight = Satelight.new(satelight_params)

    respond_to do |format|
      if @satelight.save
        format.html { redirect_to @satelight, notice: 'Satelight was successfully created.' }
        format.json { render :show, status: :created, location: @satelight }
      else
        format.html { render :new }
        format.json { render json: @satelight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /satelights/1
  # PATCH/PUT /satelights/1.json
  def update
    respond_to do |format|
      if @satelight.update(satelight_params)
        format.html { redirect_to @satelight, notice: 'Satelight was successfully updated.' }
        format.json { render :show, status: :ok, location: @satelight }
      else
        format.html { render :edit }
        format.json { render json: @satelight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /satelights/1
  # DELETE /satelights/1.json
  def destroy
    @satelight.destroy
    respond_to do |format|
      format.html { redirect_to satelights_url, notice: 'Satelight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_satelight
      @satelight = Satelight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def satelight_params
      params.require(:satelight).permit(:name1, :name2, :name3)
    end
end

app/helpers/satelights_helper.rb
module SatelightsHelper
end

app/views/satelights/_form.html.erb
<%= form_with(model: satelight, local: true) do |form| %>
  <% if satelight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(satelight.errors.count, "error") %> prohibited this satelight from being saved:</h2>

      <ul>
      <% satelight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name1 %>
    <%= form.text_field :name1 %>
  </div>

  <div class="field">
    <%= form.label :name2 %>
    <%= form.text_field :name2 %>
  </div>

  <div class="field">
    <%= form.label :name3 %>
    <%= form.text_field :name3 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/satelights/edit.html.erb
<h1>Editing Satelight</h1>

<%= render 'form', satelight: @satelight %>

<%= link_to 'Show', @satelight %> |
<%= link_to 'Back', satelights_path %>

app/views/satelights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Satelights</h1>

<table>
  <thead>
    <tr>
      <th>Name1</th>
      <th>Name2</th>
      <th>Name3</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @satelights.each do |satelight| %>
      <tr>
        <td><%= satelight.name1 %></td>
        <td><%= satelight.name2 %></td>
        <td><%= satelight.name3 %></td>
        <td><%= link_to 'Show', satelight %></td>
        <td><%= link_to 'Edit', edit_satelight_path(satelight) %></td>
        <td><%= link_to 'Destroy', satelight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Satelight', new_satelight_path %>

app/views/satelights/new.html.erb
<h1>New Satelight</h1>

<%= render 'form', satelight: @satelight %>

<%= link_to 'Back', satelights_path %>

app/views/satelights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name1:</strong>
  <%= @satelight.name1 %>
</p>

<p>
  <strong>Name2:</strong>
  <%= @satelight.name2 %>
</p>

<p>
  <strong>Name3:</strong>
  <%= @satelight.name3 %>
</p>

<%= link_to 'Edit', edit_satelight_path(@satelight) %> |
<%= link_to 'Back', satelights_path %>